### ISSUE TITLE
success apply in chinese 

### ISSUE THREAD

**Issue by v-yunbin** [ottokart/punctuator2#50]
python3 problem:
 First time failed, second time success,but get empty model.

```
rval = inputs[0].__getitem__(inputs[1:])
Total number of training labels: 2696960
Total number of validation labels: 1022336
Validation perplexity is 1.2874
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    net.save(model_file_name, gsums=gsums, learning_rate=learning_rate, validation_ppl_history=validation_ppl_history, best_validation_ppl=best_ppl, epoch=epoch, random_state=rng.get_state())
  File "/data/zyb/punctuator2/models.py", line 252, in save
    cPickle.dump(state, f, protocol=cPickle.HIGHEST_PROTOCOL)
AttributeError: module '_pickle' has no attribute 'HIGHEST_PROTOCOL'
INFO (theano.gof.compilelock): Refreshing lock /root/.theano/compiledir_Linux-4.15--generic-x86_64-with-debian-stretch-sid-x86_64-3.7.3-64/lock_dir/lock
256 0.02 Model_ep_h256_lr0.02.pcl
Building model...
Number of parameters is 14387208
Training...
PPL: 1.8218; Speed: 159.58 sps
PPL: 1.6782; Speed: 174.15 sps
PPL: 1.5590; Speed: 178.82 sps
~                                                                                                                        
~                                                                            
```

**Comment by v-yunbin** [comment]
Train succcess with python2, i think its  amazing just little text coprpus:
`不懂事 嘛 .PERIOD 就 那种 几 岁 的 时候 就 跟 男孩子 扎堆 扎针 是 在 那 玩 ,COMMA 就 感觉 小时候 的 时光 特别 好 ,COMMA 而且 觉得 小时候 的 友情 是 特别 纯真 的 又 没有 差一点 杂 杂 的 那种 不 像 长大了 就 感觉 很多 东西 都 变味 了 .PERIOD 很多 东西 都 不一样 了 ,COMMA 就 参与 什么 利益 呀 ?QUESTIONMARK `
